Generate random auction id
yshalenyk/openprocurement.auction.worker pull request #40
Opened 2019-04-05 11:36 UTC by OrysiaDrabych

2019-04-08 09:42 UTC, oleksiyVeretiuk approved these changes

2019-04-09 09:31 UTC, Scandie requested changes

2019-04-09 09:31 UTC, Scandie commented on openprocurement/auction/worker/tests/functional/main.py
> +        auction_json = json.load(_file).get('data', {})
З якою метою оголошується змінна `auction_json`?
Є сенс в тому, щоб наступні дії (стрічки 27-30) проводити в контексті роботи з файл дескриптором `_file`?

2019-04-09 09:31 UTC, Scandie commented on openprocurement/auction/worker/tests/functional/main.py
>          if auction_id:
Зайва перевірка?

2019-04-12 13:38 UTC, Scandie approved these changes

2019-04-15 13:10 UTC, merged